setClass ("NicheModel",
	representation (
		modelname="character",
#		rasterstackfit="rasterstack",
		rasterstackfit="list",
		trainprs="array",
		trainabs="array",
		testprs="array",
		testabs="array",
		trainprsvals="array",
		trainabsvals="array",
		testprsvals="array",
		testabsvals="array",
		fittedmodel="list",
		test="list",
		rasterstackpredict="list",
#		rasterstackpredict="rasterstack",
		predictfilename="character",
		xmin ="numeric",
		xmax ="numeric",
		ymin ="numeric",
		ymax ="numeric"
		),
	prototype (
		modelname="",
#		rasterstackfit=new("rasterstack", xmin=0,xmax=0,ymin=0,ymax=0,xres=0,yres=0,ncols=as.integer(0),nrows=as.integer(0),ncells=as.integer(0)),
		rasterstackfit=list(),
		trainprs= matrix(nrow=0, ncol=0),
		trainabs=matrix(nrow=0, ncol=0),
		testprs=matrix(nrow=0, ncol=0),
		testabs=matrix(nrow=0, ncol=0),
		trainprsvals= matrix(nrow=0, ncol=0),
		trainabsvals=matrix(nrow=0, ncol=0),
		testprsvals=matrix(nrow=0, ncol=0),
		testabs=matrix(nrow=0, ncol=0),
		fittedmodel = list(),
		test = list(),
#		rasterstackpredict=new("rasterstack", xmin=0,xmax=0,ymin=0,ymax=0,xres=0,yres=0,ncols=as.integer(0),nrows=as.integer(0),ncells=as.integer(0)),
		rasterstackpredict=list(),
		predictfilename="",
		xmin = 0,
		xmax = 0,
		ymin = 0,
		ymax = 0
		)
	)
