// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pjcheckcrs
bool pjcheckcrs(String crs);
RcppExport SEXP Rproj4_pjcheckcrs(SEXP crsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< String >::type crs(crsSEXP);
    __result = Rcpp::wrap(pjcheckcrs(crs));
    return __result;
END_RCPP
}
// pjtransform3
NumericMatrix pjtransform3(NumericVector x, NumericVector y, String pj_in, String pj_out);
RcppExport SEXP Rproj4_pjtransform3(SEXP xSEXP, SEXP ySEXP, SEXP pj_inSEXP, SEXP pj_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< String >::type pj_in(pj_inSEXP);
    Rcpp::traits::input_parameter< String >::type pj_out(pj_outSEXP);
    __result = Rcpp::wrap(pjtransform3(x, y, pj_in, pj_out));
    return __result;
END_RCPP
}
