# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkCRS <- function(crs) {
    .Call('Rproj4_pjcheckcrs', PACKAGE = 'Rproj4', crs)
}

.pjtransform <- function(x, y, pj_in, pj_out) {
    .Call('Rproj4_pjtransform3', PACKAGE = 'Rproj4', x, y, pj_in, pj_out)
}

